name: uncompyle6 (osx)

on:
  push:
    branches: [ python-3.6-to-3.10 ]
  pull_request:
    branches: [ python-3.6-to-3.10 ]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        os: [macOS]
        python-version: ['3.8', '3.10']
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        # Until the next xdis release
        pip install --local -e "git+https://github.com/rocky/python-xdis.git@python-3.6-to-3.10#egg=xdis"
        pip install -e .
        # Not sure why "pip install -e" doesn't work above
        # pip install click spark-parser xdis
        pip install -r requirements-dev.txt
    - name: Test uncompyle6
      run: |
        make check
