name: uncompyle6 (windows)

on:
  push:
    branches: [ python-3.3-to-3.5 ]
  pull_request:
    branches: [ python-3.3-to-3.5 ]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        os: [windows]
        python-version: [3.5]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install --disable-version-check -e .
        pip install --disable-version-check -r requirements-dev.txt
    - name: Test uncompyle6
      run: |
        make check
